project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Copyright 2023, Sara Iagnemma" 
    right: 
      - icon: github
        href: https://github.com/sfiagnemma
  title: "Sara's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - walkthrough.qmd
      - Story Samples.qmd
      - Media Law Essay.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



